<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Data Raw' => '',
    'Download' => 'Скачать',
    'ID' => '',
    'Created At' => 'Создан',
    'Data' => 'Данные',
    'Data export' => 'Экспорт данных',
    'Data requested for exporting is ready' => 'Данные, запрошенные для экспорта, готовы',
    'Export Request' => 'Запрос на экспорт данных',
    'Export Requests' => 'Запросы на экспорт данных',
    'Export request was added to queue. System will notify you when it will be done' => 'Запрос на экспорт данных поставлен в очередь. Система уведомит Вас о готовности выгрузки',
    'Exported At' => 'Дата экспортирования',
    'File' => 'Файл',
    'Files' => 'Файлы',
    'Is Exported' => 'Экспортирован',
    'Updated At' => 'Обновлен',
    'User ID' => 'Пользователь',
];
